# Generated by Django 2.2 on 2019-06-06 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('area', models.IntegerField()),
                ('l_dt', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('area', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bedrms', models.IntegerField()),
                ('bthrms', models.IntegerField()),
                ('photo_m', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajbs.Schemes')),
            ],
        ),
    ]
