# Generated by Django 2.2 on 2019-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='descp',
            field=models.TextField(default='ikk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemes',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='schemes',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='schemes',
            name='photo_m',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='schemes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flats',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
